### ISSUE TITLE
an uncertain issue about dataset in ./code/assignment_code/preprocessing.py

### ISSUE THREAD

**Issue by Imurdie** [zzwalala/Motor_Bearing_Fault_Diagnosis#1]
when create GAf images,you probably forgot to add normal data.Further more, you created normal_path and data_path(fault data),how to use them both(except combine data to a folder)?
p.s.you can reply me no matter  English or Chinese.

**Comment by zzwalala** [comment]
嗨。这个代码当时是自己为课设所用，为备份便上传到github上不曾系统整理过，也因此造成不便。现在的代码确实存在所说的这个问题。我想在当时我可能是在调用代码时将folder2img函数中现在的data_path变量换为normal_path变量后重新运行代码生成图像，生成的图片放在了同一个文件夹中。因时间久远，无法确保这样做是否正确。如未能解决问题，还请后续告知我clone下来重新验证一下这一部分的代码。

**Comment by Imurdie** [comment]
Genius.It works!
